default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV['RATE_SHELF_PASSWORD'] %>

development:
  <<: *default
  database: rate_shelf_development

test:
  <<: *default
  database: rate_shelf_test